# Generated by Django 4.1 on 2022-09-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Business", "verbose_name_plural": "Empresas"},
        ),
        migrations.AlterModelOptions(
            name="business_product",
            options={
                "verbose_name": "Business_Product",
                "verbose_name_plural": "Business_Products",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Colecciones",
            },
        ),
        migrations.AlterModelOptions(
            name="color",
            options={"verbose_name": "Color", "verbose_name_plural": "Colores"},
        ),
        migrations.AlterModelOptions(
            name="color_product",
            options={
                "verbose_name": "Color_Product",
                "verbose_name_plural": "Color_Products",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Paises"},
        ),
        migrations.AlterModelOptions(
            name="historicalbusiness",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Business",
                "verbose_name_plural": "historical Empresas",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbusiness_product",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Business_Product",
                "verbose_name_plural": "historical Business_Products",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Category",
                "verbose_name_plural": "historical Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcollection",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Collection",
                "verbose_name_plural": "historical Colecciones",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcolor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Color",
                "verbose_name_plural": "historical Colores",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcolor_product",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Color_Product",
                "verbose_name_plural": "historical Color_Products",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcountry",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Country",
                "verbose_name_plural": "historical Paises",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalindicator",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Indicator",
                "verbose_name_plural": "historical Indicadores",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Product",
                "verbose_name_plural": "historical Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreference",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Reference",
                "verbose_name_plural": "historical Referencias",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsex",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Sex",
                "verbose_name_plural": "historical Sexs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsex_business",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Sex_Busines",
                "verbose_name_plural": "historical Sex_Business",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsize",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Size",
                "verbose_name_plural": "historical Sizes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsize_product",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Size_Product",
                "verbose_name_plural": "historical Size_Products",
            },
        ),
        migrations.AlterModelOptions(
            name="indicator",
            options={"verbose_name": "Indicator", "verbose_name_plural": "Indicadores"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterModelOptions(
            name="reference",
            options={"verbose_name": "Reference", "verbose_name_plural": "Referencias"},
        ),
        migrations.AlterModelOptions(
            name="sex", options={"verbose_name": "Sex", "verbose_name_plural": "Sexs"},
        ),
        migrations.AlterModelOptions(
            name="sex_business",
            options={
                "verbose_name": "Sex_Busines",
                "verbose_name_plural": "Sex_Business",
            },
        ),
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name": "Size", "verbose_name_plural": "Sizes"},
        ),
        migrations.AlterModelOptions(
            name="size_product",
            options={
                "verbose_name": "Size_Product",
                "verbose_name_plural": "Size_Products",
            },
        ),
        migrations.AlterField(
            model_name="business",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="business",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="business_product",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="business_product",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="category",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="category",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="color",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="color",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="color_product",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="color_product",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="country",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="country",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="historicalbusiness",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbusiness",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbusiness_product",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbusiness_product",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcategory",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcategory",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollection",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollection",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcolor",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcolor",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcolor_product",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcolor_product",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreference",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreference",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsex",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsex",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsex_business",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsex_business",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsize",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsize",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsize_product",
            name="deleted_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsize_product",
            name="modified_date",
            field=models.DateField(
                blank=True, editable=False, verbose_name="Fecha de modificacion"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="product",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="product",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="reference",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="sex",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="sex",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="sex_business",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="sex_business",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="size",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="size",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
        migrations.AlterField(
            model_name="size_product",
            name="deleted_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de eliminacion"),
        ),
        migrations.AlterField(
            model_name="size_product",
            name="modified_date",
            field=models.DateField(auto_now=True, verbose_name="Fecha de modificacion"),
        ),
    ]
