# Generated by Django 4.1 on 2022-09-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_business_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsex_business",
            name="sex",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.sex",
                verbose_name="Sexo como se vende el producto",
            ),
        ),
        migrations.AlterField(
            model_name="sex_business",
            name="sex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.sex",
                verbose_name="Sexo como se vende el producto",
            ),
        ),
    ]
