# Generated by Django 4.1 on 2022-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_historicalsex_business_sex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Imagen del Producto",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Imagen del Producto",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="material",
            field=models.CharField(
                max_length=100, verbose_name="Nombre del material de producto"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.CharField(
                max_length=100, verbose_name="Nombre del material de producto"
            ),
        ),
    ]
