# Generated by Django 4.1 on 2022-09-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_historicalproduct_image_product_image_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="color_product", unique_together={("product", "color")},
        ),
        migrations.AlterUniqueTogether(
            name="sex_business", unique_together={("businnes_producto", "sex")},
        ),
        migrations.AlterUniqueTogether(
            name="size_product", unique_together={("product", "size")},
        ),
    ]
